### ISSUE TITLE
immutable metric set data and stream state should be decoupled

### ISSUE THREAD

**Issue by rib** [rib/gputop#127]
Currently we have `struct gputop_perf_query` (which mostly represents the meta data of the XML metric sets in the form of C structures, generated via oa-gen.xml) also coupled with a `uint64_t accumulator[]` array which is runtime state used in the processing of the metrics, aggregating counter deltas over a configurable period of time before evaluating the normalization equations.

One limitation of coupling these is that we can't have multiple accumulators per stream of metrics, which would be useful when we want to be able to visualize the same metrics in multiple ways at the same time, depending of accumulating for different lengths of time. For example in the web ui while plotting a trace of some metrics on a graph we want very short accumulation periods so we can plot lots of points over time for a detailed graph while we also want to show the bar graphs for counters at the same time which should update less frequently, maybe just once per second, so the values remain readable to the user.

We should aim to introduce a separate `struct gputop_perf_aggregator` that is associated with a stream of metrics instead of being coupled with the metric set descriptions.

Assuming we rename `struct gputop_perf_query` to `struct gputop_metric_set` and `struct gputop_worker_query` to `struct gputop_remote_stream` as in #126 then we could introduce a `struct gputop_perf_aggregator` that itself works with the data from a `struct gputop_remote_stream`.

The aggregator would track the uint64_t array of deltas and a period over which counter deltas are accumulated.

When the raw i915 perf samples are processed the same raw counter reports should be processed separately for each accumulator.

**Comment by sergioamr** [comment]
I am working on this with a bit of a different approach:
https://github.com/sergioamr/gputop/blob/sergio/wip/oa-pid-test/gputop/gputop-accumulator.c

**Comment by rib** [comment]
At least as far as adding a `struct gputop_oa_accumulator` that's separate from `gputop_perf_query/metric_set` this was resolved in 6979e0a63ad3e72cc2c50f7c40cec4ee22326103

Further features based on this such as the pid filtering being investigated by @sergioamr or having a separate accumulator for the slower bar graph updates can be tracked as separate issues.
