### ISSUE TITLE
Automatically list processes using the GPU in left pane

### ISSUE THREAD

**Issue by rib** [rib/gputop#144]
This would be a precursor for enabling pid based filtering of metrics, beyond the limited per-context filtering we support so far.

Based on the ability to capture batch buffer metrics using Sourab Gupta's (@sourabgu) extensions to the i915 perf kernel interface we can capture streams of metrics where the samples are tagged with a pid which in turn allows us to build up a list of processes that are actively using the GPU (and a list of contexts associated with each pid).

For reference: Sourab's kernel changes are maintained here:
https://github.com/sourabgu/linux

Anyone that looks at this can coordinate with Sourab and myself to check what branch of the kernel to work with, though I think we should aim to start including Sourab's changes under the wip/rib/oa-next branch which is currently what we point at in the gputop Build Instructions wiki page.

**Comment by djdeath** [comment]
Although the new UI doesn't list the processes using the GPU, they're visible in the timeline and per context filters.
I'm considering a special window that would be the equivalent on ```top``` with a list of processes but not sure if actually useful.
Right now, from the timeline window, you can pull out the RCS usage : 
![screenshot from 2018-01-30 21-26-11](https://user-images.githubusercontent.com/434333/35592241-48f5861a-0604-11e8-9034-6db2b0f32540.png)
