### ISSUE TITLE
Allow the web ui to open and collect perf tracepoint metrics, e.g. to visualize vblanks

### ISSUE THREAD

**Issue by rib** [rib/gputop#145]
gputop-perf.c already has initial support for opening up perf tracepoints, but we still need some extended Protocol Buffers protocol in gputop.proto and web ui support to be able to capture perf tracepoint metrics (such as vblank metrics) so we can plot these onto the traceview graphs of individual metrics.

Roughly I guess we need:
- extended protocol for opening a tracepoint, as opposed to an i915-perf stream
- The raw format for tracepoints is introspectable via debugfs and we should support reading in the (machine readable) files that describe the format of a particular tracepoint and forwarding this description to a remote ui.
- there is already be some gputop-server.c code for forwarding perf metrics (which should Just Work™ for tracepoint data) but the plumbing to handle perf messages in gputop.js and gputop-web.c is currently incomplete. (though there are some leftovers since OA metrics used to be captured based on the perf interface)
- ajax/metrics.html should have some option (just yet another toggle to start with) to enable plotting particular tracepoint data (recommend starting with vblank events). We should keep in mind ideas for improved ways to expose more tracepoints in the UI though.
- gputop.js needs a new object to track an open Tracepoint - we shouldn't just keep dumping things in the Metric object, and maybe this is a good time to split some things out of the Metric object.
- gputop-web.c needs a structure for tracking an open tracepoint, similar to, or an adaptation of `struct gputop_webc_stream`
- gputop-ui.js (which is responsible for updating the traceview graphs) is probably a good place to orchestrate requesting the server to open a perf tracepoint in response to a user action via metrics.html, and managing the lifetime of any corresponding Tracepoint object and struct gputop_webc_stream. As tracepoint data is received from the server gputop-ui.js can manage some way of plotting the data on the traceview graphs as they are updated.

Please prod me to discuss more details on this if you get to looking at this before me.

**Comment by djdeath** [comment]
Done in the new UI too.
Although we need kernel support to map timestamp from CPU to GPU.
Sourab started that work and it's working well on my machine, but not upstream : https://github.com/djdeath/linux/tree/wip/djdeath/oa-next
