### ISSUE TITLE
Uncomment SKL "Samplers Bottleneck" counter

### ISSUE THREAD

**Issue by rib** [rib/gputop#159]
For some reason the codegen for this Samplers Bottleneck counter is resulting in code that doesn't compile due to a missing symbol for the the Sampler0Bottlenect dependency. Maybe there's an inconsistency with how the camel case name with the '0' between words gets turned unto an underscore name.

**Comment by djdeath** [comment]
Fix in f602fcde9c81e0e66e5b625ce77df76807feb6c5
