### ISSUE TITLE
building kernel driver documentation page is empty

### ISSUE THREAD

**Issue by dominig** [rib/gputop#160]
The documentation invite the reader to load a page 'first' which does not exist yet.

"... The metrics gputop visualizes depend on a new drm 'i915 perf' kernel interface that's not yet upstream, so for now you need to follow these **_https://github.com/rib/linux/wiki/Build-Instructions_** first..."

The pointing page does not exist.

**Comment by rib** [comment]
Sorry, I'm not sure I can see what's wrong. The link "[https://github.com/rib/linux/wiki/Build-Instructions](https://github.com/rib/linux/wiki/Build-Instructions)" seems to be ok for me - maybe there was a temporary issue with GitHub wikis being down for some reason?

**Comment by dominig** [comment]
OK. I have found the issue. The MD notation was inverted and the pointed page was incorrect.
I have now corrected the page.
