### ISSUE TITLE
Refresh / idle handling with imgui

### ISSUE THREAD

**Issue by ocornut** [rib/gputop#172]
When I try the demo on gputop.com, some UI elements don't seem to properly refresh when clicked on, until the mouse is moved again.

As you seem to be using a scheme to let the application go idle (which is good idea), you probably want to keep refreshing 1 frame after the latest click.

The issue being quite obvious here, I wonder if perhaps depending GPU/driver setting, using double/triple buffering would affect the result, and perhaps you aren't seeing the issue on your dev machine?

(PS: if I may suggest so, I am trying to phase out the Classic imgui style It's been updated since your version of imgui, but you can call ImGui::StyleColorsDark() to switch to a be looking theme with your version)

**Comment by djdeath** [comment]
Thanks, I'll check. The backend should (like the 2 others GLFW/Gtk+) for any even trigger a couple of frames.
What OS/Browser are you using? (I haven't paid too much attention, but it probably works fine here).

**Comment by ocornut** [comment]
I'm on Windows 10, Firefox 58.0.1, running on a Laptop with GTX 1080 + Intel HD 530. Selecting either as the default GPU gets me the same problem. I also tried Chrome now and get the same problem. 

For example, clicking on "Style Editor" with the mouse still: I see the button highlighting then reverting to its normal color, but don't see the Style Editor window appearing until moving the mouse once more.
