### ISSUE TITLE
gputop-ui host/port option

### ISSUE THREAD

**Issue by eero-t** [rib/gputop#181]
Test-case:
1. run as root: GPUTOP_PORT=80 gputop
2. run as proposed by gputop: gputop-ui -h 127.0.0.1:80

Expected outcome:
* goutop-ui connects to server

Actual outcome:
* gputop-ui didn't split port number from IP address, used a default port number, and couldn't connect

If gputop-ui has an option for specifying port number, gputop server should specify correct one.

IMHO "-h" option should be reserved for command line help, not for specifying gputop-ui host address.

-> It would be better if all the tools would use same command line options for consistency.  E.g. gputop-wrapper uses "-H" for host and "-p" option for port number.

**Comment by djdeath** [comment]
I was lazy and left this out for the glfw ui...
Should be trivial to fix.
