### ISSUE TITLE
Having "RCS usage" view open without "Multi contexts" view open

### ISSUE THREAD

**Issue by eero-t** [rib/gputop#185]
"RCS usage" view can be opened from "Multi contexts" trace event view.   If I close "Multi contexts" view, "RCS usage" view also closes.

I think "RCS usage" view is hierarchically at least on same level with current data in "Multi contexts" view, i.e. it should be independent.

One possibility would be to have that data fill other half of the current CPU utilization graph.

**Comment by djdeath** [comment]
Yeah, I guess we could have a live RCS usage over the aggregation period.
That would be a new window, different from the existing one that is really tied to the timeline.

**Comment by eero-t** [comment]
What about just having the plain piechart (with mouse-over info) beside CPU utilization?

Best would be if contexts would use the same colors in all the views, including the "Select contexts" popup in "Per contexts" view, context names there could be prefixed with a little box of suitable color.

**Comment by djdeath** [comment]
So I tried to display the pie chart based on the aggregation period (which is 50ms) and I kind of find it fairly unusable/unreadable : 

https://www.youtube.com/watch?v=ye_GdoWyERE

Maybe we need a different representation. I think an live busyness for a main window would be good.
Then somewhere else a list of the main users.

**Comment by djdeath** [comment]
Global busyness : 
![busyness](https://user-images.githubusercontent.com/434333/39674934-91cfd02e-514b-11e8-95af-3f6fb65d3a39.png)

**Comment by djdeath** [comment]
New live view for usage (from the highlighted button on the left) : 
![usage](https://user-images.githubusercontent.com/434333/39676814-843ba056-5168-11e8-8c07-c14a2b25a8e4.png)

**Comment by eero-t** [comment]
> So I tried to display the pie chart based on the aggregation period (which is 50ms by default) and I kind of find it fairly unusable/unreadable (click to watch video) 

Agree, that looks pretty bad, but the new live view that you came up with looks great!

Only thing that I find a bit misleading are the view titles:
* "perf" is name of the kernel CPU performance counter sampling framework, which OA counter code doesn't use. IMHO you can drop that term completely, it's redundant
* And "i915" is the component providing this information, I think it would be better to instead use name of the  component which performance is being measured  (GPU/ GT/RCS/etc)
