### ISSUE TITLE
The files generated for drm/i915 have incorrect SPDX header comment style

### ISSUE THREAD

**Issue by jnikula** [rib/gputop#197]
All the files are prefixed with:

`/*`
` * SPDX-License-Identifier: MIT`
` *`

while the correct format for C source files is:

`// SPDX-License-Identifier: MIT`

and C header files:

`/* SPDX-License-Identifier: MIT */`

See https://www.kernel.org/doc/html/latest/process/license-rules.html

**Comment by djdeath** [comment]
I would like to retain the autogenerated warning in those files.
What should the format look like in that case?

**Comment by jnikula** [comment]
Add a free form comment after the single line SPDX header that has format requirements. (N.b. I didn't make these up, I wouldn't have used // but I don't want to start deviating either.)

C source:

```
// SPDX-License-Identifier: MIT
/*
 * Copyright © 2018 Intel Corporation
 *
 * Autogenerated file by GPU Top : https://github.com/rib/gputop
 * DO NOT EDIT manually!
 */

```
C header:

```
/* SPDX-License-Identifier: MIT */
/*
 * Copyright © 2018 Intel Corporation
 *
 * Autogenerated file by GPU Top : https://github.com/rib/gputop
 * DO NOT EDIT manually!
 */

```
