### ISSUE TITLE
Use of GPUTop for multi-GPU enviroment

### ISSUE THREAD

**Issue by peter197321** [rib/gputop#199]
I am starting with GPUTop, and my system has two embedded gpus - how to monitor both of them?

**Comment by djdeath** [comment]
GPUTop only works with Intel GPUs. Has your system more than one Intel GPU?

**Comment by peter197321** [comment]
Unfortunately I use other vendor GPU (verisilicon). Is it working for this
as well?
What needs to be adapted to function for that vendor?
By just running it identifies GPU and I am not of functioning for this GPU.
GPU and it's driver supports Khronos API such OpenGL or OpenCL.

Dne pá 19. 4. 2019 0:10 uživatel Lionel Landwerlin <notifications@github.com>
napsal:

**Comment by djdeath** [comment]
Unfortunately GPUTop only works on Intel GPUs.
There are no plans to support other vendors at the moment.

Sorry :(
