### ISSUE TITLE
Monitor OpenCL activity on GPU

### ISSUE THREAD

**Issue by peter197321** [rib/gputop#200]
please how to run and setup GPUTop for monitoring OpenCL code (kernels) execution and get perfromance and its profiling

**Comment by djdeath** [comment]
If you launch your OpenCL application from the console, you can, for example, get some data sampled using the following command : 
```
gputop-wrapper -m RenderBasic -c GpuCoreClocks,EuActive,L3Misses,GtiL3Throughput,EuFpuBothActive -- ./my-application
```

What kind of information are you after?

**Comment by peter197321** [comment]
At least to check the kernels run on GPU.
Ideally GPU occupancy as well ...

Dne pá 19. 4. 2019 0:18 uživatel Lionel Landwerlin <notifications@github.com>
napsal:

**Comment by djdeath** [comment]
So this tool doesn't let you explore the OpenCL/OpenGL kernels.
It does provide utilization data for the various parts of the GPU like the execution units.

You can get the data for the entire system (all applications) with : 
```
gputop-wrapper -m RenderBasic -c EuActive
```

You can also get the data for a particular application with : 
```
gputop-wrapper -m RenderBasic -c EuActive -- /path/to/my/application
```

There are lots other metrics. Metrics are grouped by sets. You can list all the sets with : 
```
gputop-wrapper -m list
```

Then list the metrics of a particular set (here ComputeBasic) with : 
```
gputop-wrapper -m ComputeBasic -c list
```

**Comment by djdeath** [comment]
Hopefully that answers your question. Feel free ask more details :)
