### ISSUE TITLE
meson.build web dependencies wrongly included?

### ISSUE THREAD

**Issue by likewise** [rib/gputop#202]
In `meson.build`, the web dependencies seem to be added when build_webui is false. This seems wrong. Shouldn't this be: `if build_webui` ?

<pre>
if *not* build_webui
  libuv_dep = subproject('libuv').get_variable('libuv_dep')
  wslay_dep = subproject('wslay').get_variable('wslay_dep')
  h2o_dep = subproject('h2o').get_variable('h2o_dep')

  subdir('server')
  subdir('wrapper')
  subdir('utils')
endif
</pre>

**Comment by djdeath** [comment]
Hmm no because the webui uses the websocket stack available in webbrowsers implementations.
So we don't need libuv/wslay/h2o.
Server is obviously as native tool as well as wrapper & utils (a single tool to deal with HW configurations on the command line).

**Comment by likewise** [comment]
Thanks. I'm trying to build this under Yocto so my build environment for this build is minimized to what the package actually requires. I'll close the issue but bother you privately. :)
