### ISSUE TITLE
Simplifying web architecture

### ISSUE THREAD

**Issue by sergioamr** [rib/gputop#34]
Currently the web code is divided in two parts,
1. Javascript UI
2. Emscripten generated code from C which uses a webworker that creates a websocket to communicate 
with the GPUTOP server using protobuffers.

The UI talks to the webworker using a JSON RPC functionality. For every UI interaction that we need to add we have to create several functions to enable interaction. 

The idea is to simplify this system by removing the UI interaction from the webworker and having the native JS being able to communicate seamlessly with the GPUTOP server.

**Comment by rib** [comment]
The foundation for this new web ui has now landed in master, superseding the old web ui.
