### ISSUE TITLE
Querying the environment within an ifunc resolver yields unexpected behaviour

### ISSUE THREAD

**Issue by matt-auld** [rib/gputop#42]
Running GPU top on Fedora 23 results in a crash. Doing a little digging it appears to be the related to accessing the environment from within the ifunc resolver. After some research is seems that calling library routes within the resolver is _not_ allowed, as ifunc runs as the program is just starting, so behaviour is not well defined when accessing the environment. To resolve this we will now need to use LD_PRELOAD to load our GL hooks, and abandon the ifunc work :(

**Comment by rib** [comment]
Thanks for digging into this. This has now been resolved in your #43 pull request (merged)
