### ISSUE TITLE
web: need to represent gaps in traced metrics from context switches

### ISSUE THREAD

**Issue by rib** [rib/gputop#79]
When enabling per-context mode there will be gaps in our received metrics corresponding to work executed for other gpu contexts than the one we're monitoring.

Firstly note that there are a few different sampling periods involved in our processing of metrics:
1. The sampling period/exponent we program the OA unit with so the hardware writes our counter snapshots.
2. The period which we aggregate raw reports over before triggering a UI update. The hardware sampling period has to be lower than the the update period.

Aggregation is done by taking sequential pairs of raw OA counter reports and calculating the deltas between raw counters and adding those to a 64bit accumulation buffer. The normalization equations are evaluated based on one of these 64bit accumulation buffers.

The parsing of OA reports done in gputop-web.c doesn't currently understand about OA reports that are generated in response to a context switch. Looking at gputop-perf.c:read_i915_perf_samples() shows how we do consider context switches in the code for presenting metrics in the ncurses UI.

If a context switch happens we need to immediately forward an update. (It's not a problem that we will have accumulated fewer reports at this point)

The rendering/updating of the trace graphs then needs to detect gaps between the start/end timestamps of sequential updates and if there's a gap it should draw some markers to represent the context switches.

**Comment by djdeath** [comment]
I think the timeline fulfill that description.
