### ISSUE TITLE
does gputop (+- per-context mode) work with the Mesa Vulkan driver?

### ISSUE THREAD

**Issue by rib** [rib/gputop#96]
It should Just Work™ but we should test this

**Comment by matt-auld** [comment]
Drum roll please....

Can confirm that the per-context mode seems to work as expected, which should of no surprise :smiley: 

Tested on `Fedora 23`, running with `vkcube` as the test program.

**Comment by rib** [comment]
Wooo! Glad to provide an excuse to play with Vulkan :-)
